# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))
from openpibo import __version__ as VERSION

# 기기 밖(PC·컨테이너)에서도 빌드되게, 설치 안 된 하드웨어·모델 패키지만 autodoc 용 가짜로 바꾼다.
# 기기에는 다 있으므로 기기 빌드 결과는 그대로다
import importlib.util
autodoc_mock_imports = [m for m in (
    'bs4', 'serial', 'openpibo_models', 'openpibo_dlib_models', 'openpibo_detect_models',
    'board', 'busio', 'digitalio', 'adafruit_ssd1306', 'adafruit_rgb_display',
    'soundfile', 'picamera2', 'libcamera', 'dlib', 'openvino', 'rpi_ws281x', 'RPi', 'pyzbar',
    'mediapipe', 'onnxruntime', 'tflite_runtime', 'sherpa_onnx', 'requests', 'cv2', 'spidev',
) if importlib.util.find_spec(m) is None]

# -- Project information -----------------------------------------------------

project = 'OPENPIBO'
copyright = f'2026 THEMAKER. All rights reserved. openpibo-python-{VERSION}'
author = 'Circulus'

# The full version, including alpha/beta/rc tags
release = VERSION


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
html_baseurl = 'https://themakerrobot.github.io/openpibo-python.pibrain/_modules/openpibo'
extensions = [
    'myst_parser',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.autosummary',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
]
myst_enable_extensions = ['html_image']   # 블록 가이드의 <img width=…> 를 Sphinx 그림으로(파일이 _images 로 복사된다)
autosectionlabel_prefix_document = True   # 페이지마다 같은 제목(도구 등)이 있어도 겹치지 않게

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ko'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# Furo(MIT) — 밝게·어둡게는 브라우저 설정을 따른다. 색은 IDE 와 같게(노랑 포인트, 파랑 링크).
# 외부 글꼴·CDN 을 쓰지 않아 기기(AP 모드, 인터넷 없음)에서도 그대로 보인다
html_theme = 'furo'
html_title = 'PiBrain 도움말'
html_theme_options = {
    'sidebar_hide_name': False,
    'navigation_with_keys': True,
    'light_css_variables': {
        'color-brand-primary': '#2563eb',
        'color-brand-content': '#2563eb',
        'color-brand-visited': '#2563eb',
        'font-stack': '"Pretendard", "Apple SD Gothic Neo", "Malgun Gothic", "Noto Sans KR", system-ui, -apple-system, "Segoe UI", sans-serif',
        'font-stack--headings': 'var(--font-stack)',
        'font-stack--monospace': '"D2Coding", "JetBrains Mono", Consolas, "SF Mono", ui-monospace, monospace',
        'color-background-secondary': '#f5f6fa',
        'color-sidebar-background': '#f5f6fa',
        'color-sidebar-item-background--current': 'rgba(37, 99, 235, .08)',
        'color-sidebar-link-text': '#4a5163',
        'color-sidebar-link-text--top-level': '#4a5163',
        'color-admonition-title--note': '#2563eb',
        'color-admonition-title-background--note': 'rgba(37, 99, 235, .08)',
        'color-admonition-title--tip': '#16a34a',
        'color-admonition-title-background--tip': 'rgba(22, 163, 74, .08)',
    },
    'dark_css_variables': {
        'color-background-primary': '#1a1e27',
        'color-background-secondary': '#222733',
        'color-sidebar-background': '#1f232d',
        'color-sidebar-item-background--current': 'rgba(251, 201, 45, .10)',
        'color-sidebar-link-text': '#b4bac8',
        'color-sidebar-link-text--top-level': '#b4bac8',
        'color-admonition-title--note': '#fbc92d',
        'color-admonition-title-background--note': 'rgba(251, 201, 45, .10)',
        'color-brand-primary': '#fbc92d',
        'color-brand-content': '#fbc92d',
        'color-brand-visited': '#fbc92d',
    },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_favicon = '_static/icon.png'
html_css_files = ['mycss.css']
