#!/bin/sh -e
#
# recovery usb
if [ -f /media/usb/update.zip ]; then
  sudo unzip /media/usb/update.zip -d /home/pi/
  sudo bash /home/pi/_update
  exit 0
fi

# hostname management
rpi_serial=$(grep "Serial" /proc/cpuinfo | awk '{print $3}' | rev | cut -c -8 | rev)
if [ $rpi_serial != "$(hostname)" ]
then
  sudo hostnamectl set-hostname --static ${rpi_serial}
  echo "127.0.0.1 localhost" > /etc/hosts
  echo "::1       localhost ip6-localhost ip6-loopback" >> /etc/hosts
  echo "ff02::1   ip6-allnodes" >> /etc/hosts
  echo "ff02::2   ip6-allrouters" >> /etc/hosts
  echo "127.0.0.1 ${rpi_serial}" >> /etc/hosts
  sudo shutdown -r now
fi

mkdir -p /home/pi/code
mkdir -p /home/pi/myimage
mkdir -p /home/pi/myaudio
mkdir -p /home/pi/mymodel

# motor init
#servo init

# ap start
echo "START - ap-start"
sudo /home/pi/openpibo-os/system/hotspot.sh start

# network init
echo "START - booting.py"
#/etc/systemd/system/booting.service
sudo systemctl start booting.service

# run server
echo "START - run_ide.py"
#/etc/systemd/system/ide.service
sudo systemctl start ide.service

# classifier server
# echo "START - classifier.py"
#/etc/systemd/system/classify.service
# sudo systemctl start classify.service

# Amp init
#sudo gpio mode 7 out
#sudo gpio write 7 1

sudo iw wlan0 set power_save off
#sudo iw ap0 set power_save off
exit 0
