#!/bin/sh -e
#
# recovery usb
if [ -f /media/usb/update.zip ]; then
  sudo unzip /media/usb/update.zip -d /home/pi/
  sudo bash /home/pi/_update
  exit 0
fi

# hostname management
rpi_serial=$(grep "Serial" /proc/cpuinfo | awk '{print $3}' | rev | cut -c -8 | rev)
if [ $rpi_serial != "$(hostname)" ]
then
  sudo hostnamectl set-hostname --static ${rpi_serial}
  echo "127.0.0.1 localhost" > /etc/hosts
  echo "::1       localhost ip6-localhost ip6-loopback" >> /etc/hosts
  echo "ff02::1   ip6-allnodes" >> /etc/hosts
  echo "ff02::2   ip6-allrouters" >> /etc/hosts
  echo "127.0.0.1 ${rpi_serial}" >> /etc/hosts
  sudo shutdown -r now
fi

# ap start
sudo /home/pi/openpibo-os/system/wifi-ap-sta run

# network init
sudo python3 /home/pi/openpibo-os/system/booting.py &

# run server
cd /home/pi/openpibo-os/ide;sudo node main.js &

sudo iw wlan0 set power_save off
sudo iw ap0 set power_save off
exit 0
